spring:
  profiles:
    active: local
    include: my
  jpa:
    hibernate:
       ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        # show_sql: true
        format_sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  mvc:
    static-path-pattern: /images/**

logging.level:
  org.hibernate.SQL: debug
#  org.springframework.web: TRACE

file:
  dir: /Users/bagchanbyeong/Documents/File/

